# Generated by Django 3.2.5 on 2021-09-20 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projectname', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(default='passwd', max_length=6)),
                ('description', models.CharField(max_length=50, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScurmBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=50)),
                ('Task_Description', models.CharField(max_length=500)),
                ('Dead_line', models.DateField()),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In progress', 'In progress'), ('Done', 'Done')], default='Todo', max_length=20)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classnote.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
